#Copyright (c) 2021 swampmonster
#
#SPDX-License-Identifier: MIT
#

identifier: plonck_rev_a
name: plonck rev A
type: mcu
arch: arm
toolchain:
  - zephyr
  - gnuarmemb
  - xtools
supported:
  - adc
  - usb_device
  - ble
  - ieee802154
  - pwm
  - watchdog
